name: flutter_tappay_spaceshare
description: A federated Flutter plugin for TapPay integration with SpaceShare.
version: 0.0.1
homepage: https://example.com
repository: https://github.com/WeiHuangTaiwan/flutter_tappay_spaceshare.git
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.spaceshare.flutter_tappay_spaceshare
        pluginClass: FlutterTappaySpacesharePlugin
      ios:
        pluginClass: SwiftFlutterTappaySpacesharePlugin
      web:
        pluginClass: FlutterTappaySpaceshareWeb